### ISSUE TITLE
Allow callers to supply a custom median line length

### ISSUE THREAD

**Issue by jayaddison** [JulienPalard/textunwrap#1]
The default `median_len=70` works well for much text wrapped at the commonly-used 80-character line length limit; it could be useful in some cases to allow users to supply a custom median line length.

**Comment by JulienPalard** [comment]
PR welcome :)

**Comment by JulienPalard** [comment]
Wow this project was covered in dust, thanks for shaking it a bit :)

**Comment by JulienPalard** [comment]
Released textunwrap==0.1.3 \o/

**Comment by jayaddison** [comment]
Great stuff, thanks!  Glad to help :)
